name: Flutter Build (Android + iOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache Flutter & Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Flutter doctor
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Setup keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/key.jks
          echo "storeFile=key.jks" > android/app/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/app/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/app/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/app/key.properties

      - name: Verify keystore files
        run: |
          ls -l android/app/key.jks android/app/key.properties 
    

      # üü¢ Build Android APK
      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          echo "$SERVER_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -P $SERVER_PORT build/app/outputs/flutter-apk/app-release.apk \
            $SERVER_USER@$SERVER_HOST:/home/deploy/workspace/hbmarket/mobile
          rm key.pem 

      # üçè Build iOS app (unsigned)
      - name: Build iOS App (unsigned)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS app artifact (.app)
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-app
          path: build/ios/iphoneos/Runner.app

            # 5Ô∏è‚É£ Private key-i hazƒ±rlamaq v…ô SCP il…ô upload
